### ISSUE TITLE
Build date in ota.json is higher than build date of gaaps release

### ISSUE THREAD

**Issue by bilemke** [Archfx/duo-de#105]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

Looks like https://raw.githubusercontent.com/Archfx/duo-de/main-15/config/ota.json is being updated with the "date" of the build  date/time of the vanilla version which appears to be built after the gapps version.

2024.11.24 gapps release build.prop file's "ro.system.build.date.utc":
ro.system.build.date.utc=1732495185

2024.11.24 vanilla release build.prop file's "ro.system.build.date.utc":
ro.system.build.date.utc=1732503279

### Expected Behavior

Ota update completes, and doesn't detect update available again

### Current Behavior

Ota update completes, and then same ota update is detected as available

### Possible Solution

Looks like https://raw.githubusercontent.com/Archfx/duo-de/main-15/config/ota.json is being updated with the "date" of the build  date/time of the vanilla version which appears to be build after the gapps version.

Either update ota.json with date/time of the gapps build or set "ro.system.build.date.utc" in the vanilla build to be the same as the gapps build when building (assuming gapps is always built first with vanilla being built second).

Or another option, use two different ota json files (one for each variant).

### Steps to Reproduce

Running gapps release:
1. Run system update, find update
2. Download and install update, reboot
3. Check for update, same update found

**Comment by Archfx** [comment]
Nice observation. I was looking for the reason behind this but couldn't notice this. Several of the last builds were performed in two steps, 
`build Gapps > test > OK > build Vanilla > update OTA `. 
This introduced the updater issue. 

Thanks for noticing this and will fix it in subsequent updates.
