### ISSUE TITLE
Phone call app not completing process when trying to make a LTE call.

### ISSUE THREAD

**Issue by Archfx** [Archfx/duo-de#110]
### Moved from a Discussion
<div type='discussions-op-text'>

<sup>Originally posted by **@orion14794** November 28, 2024</sup>
Has anyone experience this issue? I tried to place a call and it won't proceed. I switched the network settings to LTE from 3G (didn't test if 3G calls are able.) rebooted. Tried to place a call (sim card is active btw) and app hangs the attempt. 
(Update) 3G calls and sms works but not LTE...  Hope there is a fix for it.</div>

**Comment by Archfx** [comment]
@orion14794 I assume you are using a Duo2. Vo-LTE is not completely reverse-engineered yet. However, you can get it to work by following the steps outlined in [here](https://github.com/Archfx/duo-de/discussions/81) under the IMS settings.

**Comment by Archfx** [comment]
@Ethanol10 the latest image [v2024.11.27](https://github.com/Archfx/duo-de/releases/tag/v2024.11.27) is bult without the Vo-LTE-fix. Can you please confirm if Vo-LTE works without the fix? Thanks.

**Comment by Ethanol10** [comment]
Yeah, currently using this version to make calls, seems to work fine.
