### ISSUE TITLE
Issue when flashing system image

### ISSUE THREAD

**Issue by jeddy877** [Archfx/duo-de#116]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Unlocked Surface Duo 2 256GB
- GSI version: 15
- Vendor version:?

### Expected Behavior

For the GSI system image to flash successfully. I followed the steps/commands exactly.

### Current Behavior

Failed to flash. Resizing 'system_b' 'Not enough space to resize partition '

### Steps to Reproduce

1. 
2. 
3.

**Comment by wilhelmstroker** [comment]
https://github.com/Archfx/duo-de/discussions/36

the steps mentioned there worked for me when I had the same error.

**Comment by jeddy877** [comment]
That appears to be working. Thanks brother. 

Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Dec 4, 2024 at 4:46 PM, Aruna | ***@***.***> wrote:   


Closed #116 as completed.
