### ISSUE TITLE
Unable to establish passkey

### ISSUE THREAD

**Issue by oilcan-productions** [Archfx/duo-de#120]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 2
- GSI version: treble_arm64_bgN-userdebug 15 AP3A.241105.008 eng.aruna.20241129.203334
- Vendor version:

### Expected Behavior

Use Google or Microsoft Authenticator to add a passkey and use passkey authentication 

### Current Behavior

The passkey prompt never shows up

### Steps to Reproduce

1. Open authenticator or chrome
2. Chose login using passkey
3. 
![Screenshot_20241206-083631](https://github.com/user-attachments/assets/02982472-6fcb-4fb9-be31-bcf0b7437e5f)

**Comment by Archfx** [comment]
Looks like you have multiple devices registered on the Google's end due to flashing the DUO-DE multiple times.

Goto [myaccount.google.com/device-activity](https://myaccount.google.com/device-activity) and remove the previous instances of your device, just keep the latest one that was synced with the google servers.

**Comment by oilcan-productions** [comment]
@Archfx   Reopening this one. Finally got around to testing this out. I have removed all the extra devices. Same thing happens for Google Accounts but also for other accounts with Pass Keys. I tried Chrome and Edge Chromium and Firefox the behavior is similar in each browser, the Security window does not pop up. It is the same behavior on the December build and the January beta build.
