### ISSUE TITLE
Brightness slider once touched slides back automatically to lowest level and could not be adjusted without restart

### ISSUE THREAD

**Issue by NareshCal** [Archfx/duo-de#123]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

Brightness adjustment thru the  'slider' in settings should be adjustable as needed.

### Current Behavior

When I try to adjust brightness thru settings the slider automatically slides back to lowest level and could not be adjusted agains without restarting the device (Surface Duo 2)

### Possible Solution

Unknown

### Steps to Reproduce

1. Go to settings by pulldown
2. Try to adjust display brightness by adjusting /sliding the slider for brightness
3. The behavior reported in bug report requires 'Restart' to get back brightness setting. Maybe brightness setting is kept non-adjustable and only at one level in the code.

**Comment by Ethanol10** [comment]
Hmm, I'm not able to replicate this, the slider seems to work as intended.

**Comment by Archfx** [comment]
I also couldn't replicate this. Does anyone else have this issue?

PS: This could be an issue on the touch panel of the particular unit.
