### ISSUE TITLE
force circle to search apps wont work

### ISSUE THREAD

**Issue by Clanceeinfinity** [Archfx/duo-de#132]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: duo2
- GSI version: v2024.12.16
- Vendor version:

### Expected Behavior

using apps to force cts to open should work fine and open circle to search.

### Current Behavior

They don't.

### Possible Solution

i found this on the github on the biggest force cts app, maybe this could be changed on the duo2 to make these apps work.
https://github.com/parallelcc/MiCTS/issues/17

### Steps to Reproduce

1. download a cts app
2. tap it
3. doesn't open

### Additional context

I don't know if it's possible to make these changes to the gsi, if not just delete this bug report.

**Comment by Archfx** [comment]
It looks like this application requires the device to be rooted, which you have to do manually.

**Comment by Clanceeinfinity** [comment]
normally not, only if the option is set to false where i shared the link. On my unrooted tab s7 it works fine
