### ISSUE TITLE
Pen Charger on Device Charge does not work

### ISSUE THREAD

**Issue by Ethanol10** [Archfx/duo-de#135]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 2
- GSI version: 2024.12.21
- Vendor version:
 

### Expected Behavior

When the option is enabled, the device should turn on the pen charger when the user plugs the device in to mains. Similarly, the pen charger should automatically turn off when the device stops receiving power from mains.

### Current Behavior

The option seemingly does nothing. When the Pen charger is enabled manually, and then this option is toggled, the code to disable the pen charger is run, but the device fails to recognise that the device is currently being charged and does not turn on the charger. 

Occasionally, the device will turn the charger on but never turn it off.

### Possible Solution

Unsure, in development builds without Gapps, this functionality works fine. I will try to fix up this issue as soon as I can. 

### Steps to Reproduce

1. Enable the option in duo-de settings.
2. Observe the pen not charging when plugged in.

### Additional context

Broadcast receiver seems to be registering fine, but the device refuses to recognise that it's charging, is BatteryService the best way to monitor this? Maybe we should use the sticky broadcast?

**Comment by Ethanol10** [comment]
Aight, i think I know the problem now. Will see when I rebuild and repatch with @Archfx

**Comment by Archfx** [comment]
> Aight, i think I know the problem now. Will see when I rebuild and repatch with @Archfx

Let me know when you update it.  I will queue a release!
