### ISSUE TITLE
Automatic active screen setting isn't working at all

### ISSUE THREAD

**Issue by itsleemcguire** [Archfx/duo-de#137]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

The automatic mode doesn't switch the screen at all when flipping the device. Is this a bug? Autorotate on or off doesn't affect it.

### Current Behavior

 X

### Possible Solution

X

### Steps to Reproduce

1. 
2. 
3. 
 D

**Comment by Archfx** [comment]
When you switch to automatic mode, you have to change the posture of the device so that it registers a change. Otherwise it stays in the same setting untill it registers a change. I will update the logic to bypass this in future.

PS: check the ‘DUO-DE treble settings’ if you have enabled a default screen for phone mode, I think that is whats happening on your device. Default screen feature is mitigation for duo2 touch issue. It will be removed once that particular issue is fixed.

**Comment by itsleemcguire** [comment]
Wait I'm confused, so the "default screen" feature is meant to be only for duo2 problems? As I'm using it to have my duo 1 have the dual screen mode with phone unfolded, and then turning it into phone mode it defaults to forcing only the right screen on, which is perfect for that infuriating thing the duo does in phone mode where it turns off the screen you're looking at (the one pointing "up" , and you flip it around and it turns of that screen instead, almost like it's gyroscope is getting confused. )
So that default screen feature was fantastic for locking the screen, but it was annoying to go into the settings every time and change it when I wanted to like, take a picture for example. 

But now you are saying you will remove this feature and have only the quick settings tile? Because this seems like a much worse system. Unless I'm missing something. With the quick settings tile it forces for example the right screen only, similar to the "default screen" but when you unfold the duo it doesn't active the other screen, so you're left with a black screen until you tap the quick tile a bunch of times to get the right option?  The same with having both screens active, if I fold the duo it doesn't change into "phone mode" , it just has both screens active and receiving touch input. This is a much more cumbersome experience than the way I may have been accidentally/incorrectly using the other feature. I must be missing something?

**Comment by Archfx** [comment]
I think you got confused. The quick-setting tile will not be removed. The default display feature available on the `DUO-DE Treble Settings` is currently there to fix the touch issue for Duo2. For Duo1, you get the same functionality as the manual quick-setting tile, but it will not be removed if users want it as well.

**Comment by itsleemcguire** [comment]
The quick settings tile and treble settings work differently on duo1 and the treble settings one works so much better, as I tried to explain

**Comment by itsleemcguire** [comment]
The new update has really screwed with this now, It used to be that having it in phone mode it would always use the right screen if set to Right screen only in Duo settings (and switch on both screens when unfolded).  Now taking it out of my pocket it always activates the screen facing away from my face when turned on, and flipping it over inverts to the other screen. This makes the phone infuriating to use. 

This is with posture set to automatic in the quick settings, and "right only" in duo de settings.
If I set it to "right only" in quick settings then it doesn't switch on the other screen when unfolded, and it's not a good experience to have to change the quick settings every single time I fold and unfold, when the previous way was automatic.
