### ISSUE TITLE
Disable hinge gap does not allow resizing of active app windows work as in Stock 12L on SD2

### ISSUE THREAD

**Issue by NareshCal** [Archfx/duo-de#138]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 2
- GSI version: v2024.12.21
- Vendor version: 

### Expected Behavior

Scroll bar at hinge is visible and could be used to resize/move active app on desktop . 

### Current Behavior

Scroll bar at hinge should is visible and could be used to resize/move active app on desktop , which is missing. 

### Steps to Reproduce

1. Settings--> DUO-DE Treble Settings --> DUO-DE features ---> disable hinge gap (disabled using radio button
2. 
3.

**Comment by Archfx** [comment]
Reboot the device, it will allow you to resize windows (Step 5).
