### ISSUE TITLE
Desktop mode enabled, windows not floating 

### ISSUE THREAD

**Issue by fdalleva** [Archfx/duo-de#26]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: surface duo
- GSI version: 
- Vendor version:

### Expected Behavior

Desktop mode is enabled, floating windows appear diabled

### Current Behavior

As above

### Steps to Reproduce

1. Enable desktop mode
2. 
3.

**Comment by Archfx** [comment]
Hi,

Can you please enable the following settings from the **developer options**,  and let me know? 

- Force activities to be resizable 
- Enable freeform windows
- Enable non-resizable in multi-window

It looks like vendor overrides for floating windows are not applied during the build to enable it by default.  I will fix this in the next release

**Comment by JengaMasterG** [comment]
I currently switched from 12L and I am seeing this issue on the newest build (2024.09.13). Desktop mode is enabled, and the developer options to support desktop mode are enabled:
Force activities to be resizable
Enable freeform windows
Enable non-resizable in multi-window

### Update: 
Observed fix: turn off developer options listed above. Disable Desktop Mode from Home Settings. Restart Duo 1. Go into settings, see the developer options are now enabled. Enable Desktop Mode from Home Settings.
