### ISSUE TITLE
Single screen typing

### ISSUE THREAD

**Issue by fdalleva** [Archfx/duo-de#29]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: surface duo
- GSI version: 
- Vendor version:

### Expected Behavior

Typing should happen as per normal. The folded back screen should be ignoring accidental touch events

### Current Behavior

When the screen is folded back, typing on the one screen stops when you touch the back screen.

### Possible Solution

Ignore touch events on the back screen when folded

### Steps to Reproduce

1. Fold screen back, use in single screen mode
2. Your fingers will touch the back screen when typing on the front screen
3. Try type

**Comment by Archfx** [comment]
I discussed with Thai about this. To fix this little bit of experimentation is needed. I will Debug this over a weekend. If Thai comes with a fix early,  I will add it to the next release.

**Comment by fdalleva** [comment]
Awesome thanks

**Comment by Archfx** [comment]
This issue is fixed in the latest release, from the next release onwards, I plan to have two separate images for duo1 and duo2 due to this touch issue. Duo1 and Duo2 have different touch drivers and need to have separate images.

**Comment by fdalleva** [comment]
Thanks it's working now
