### ISSUE TITLE
Can't open IMS apk after install

### ISSUE THREAD

**Issue by Jokez2785** [Archfx/duo-de#30]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: SD 1 and SD2
- GSI version: 2024.07.14
- Vendor version:

### Expected Behavior

Click on install IMS APK forQualcomm vendor it creates a download named IMS APK. Click to install and reboot

### Current Behavior

Click on install IMS APK forQualcomm vendor it creates a download named IMS APK. Click to install but says can't open file. Cell signal keeps dropping can make or receive call/text.

### Steps to Reproduce

1. 
2. 
3. 

### Additional context

Tied every version, but could only get aosp-arm64-ab-vanilla-14.0-20240609.img.xz to install the IMS APK. Can't update using OTA using this version.

**Comment by Archfx** [comment]
aosp-arm64-ab-vanilla-14.0-20240609.img.xz  is an old version, please try updating to the latest.

**Comment by Jokez2785** [comment]
I tried all version even the one you released yesterday. but since I can't get the IMS apk to open  I can't make or receive call/sms. Any other fix?

**Comment by Archfx** [comment]
Is this the same issue? https://github.com/ponces/treble_aosp/issues/107
Looks like it. 

It looks like the [phh](https://github.com/phhusson/) is updating the IMS settings. We have to wait until the updates get propagated via [ponces](https://github.com/phhusson/).

**Comment by Jokez2785** [comment]
on  the older version 6-9-24 is works file with the sim. just the newer releases for whatever reason I can't install the IMS.APK fle once it downloaded. So I would say the its not the same issue. Any way to manually extract the IMS apk files on the older version? I looked everywhere but could find a how to or find the files. I do have root.

**Comment by Archfx** [comment]
20240609 is based on `android-14.0.0_r15`, latest versions are based on `android-14.0.0_r54`. `_r54` is a significant update and there are some critical changes to "IMS settings" from the original treble repo.

Unfortunately, in order to duo-de to incorporate these changes, [treble_aosp](https://github.com/ponces/treble_aosp) needs to be updated first, until then only option is to use 20240609.

**Comment by Jokez2785** [comment]
OK. I figured something changed. I can wait an update. Thanks for keeping the SD alive

**Comment by Archfx** [comment]
Can you check whether your issue is solved with [v2024.07.16](https://github.com/Archfx/duo-de/releases/tag/v2024.07.16). This bypassed ponces modifications and incorporates Trebledroid latest updates to the IMS settings.

**Comment by Jokez2785** [comment]
Ok we I get a free moment I will try on my SD1 and let you know

**Comment by Jokez2785** [comment]
I was able to open the IMS apk file but gave an error App not installed as package conflicts with an existing package

**Comment by Jokez2785** [comment]
![Uploading 020240716_095058_lmc_8.4.jpg…]()

**Comment by Archfx** [comment]
The above link is corrupted, however, I assume the above issue is due to the release keys and you cannot replace the APK without a proper signature. TrebleDroid is getting some modifications to bypass this, let's see how it goes.

**Comment by Jokez2785** [comment]
OK understood

**Comment by Archfx** [comment]
Please check on the latest release regarding this.

**Comment by Jokez2785** [comment]
Yes This fixed the issue with ims apk not being able to install. Tried it on my SD1. Once I backup my SD2 I will try the new release. And let you kmow

**Comment by Archfx** [comment]
Thanks for the update!!
