### ISSUE TITLE
camera app crashes 

### ISSUE THREAD

**Issue by sdny10000** [Archfx/duo-de#31]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: duo 1
- GSI version: 
- Vendor version: 20240716

i am using ab version for duo 1, installed using DSU. camera app keeps crashing. If I install the original google camera app, it opens and functions fine, except that it's upside down. images look squeezed too.

### Expected Behavior

regular camera

### Current Behavior

i am using ab version for duo 1, installed using DSU. camera app keeps crashing. If I install the original google camera app, it opens and functions fine, except that it's upside down. images look squeezed too.

### Steps to Reproduce

1. 
2. 
3. 
i am using ab version for duo 1, installed using DSU. camera app keeps crashing. If I install the original google camera app, it opens and functions fine, except that it's upside down. images look squeezed too.

**Comment by Archfx** [comment]
By default you might find two camera apps in the app drawer, Please use the AOSP version and ignore the other one. You can hide the crashing app from the `home settings` if you want. 

In desktop mode, the camera image won't be reshaped with the AOSP app that comes on the ROM by default.
