### ISSUE TITLE
Build can not be installed on my duo2

### ISSUE THREAD

**Issue by Clanceeinfinity** [Archfx/duo-de#35]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device:  duo2, 8/128gb model
- GSI version: aosp-arm64-ab-gapps14.0-20240725 or in other words the latest build
- Vendor version:

### Expected Behavior

typing .\fastboot flash system aosp-arm64-ab-gapps14.0-20240725.img should work, it should install the system image i guess...

### Current Behavior

i followed the instructions and everything worked fine, my bootslot is A so i deleted b, worked fine. then i did .\fastboot flash system aosp-arm64-ab-gapps14.0-20240725.img and first it told me FAILED (remote: 'Not enough space to resize partition'), i looked up a video on youtube and the guy said you have to delete your actual bootslot, in my case bootslot a. I did that, now it says FAILED (remote: 'No such file or directory'). I also tried the second newest build, it resulted in the same issue.

### Steps to Reproduce

1. unlock bootloader of a duo2
2. follow instructions on the page
3. i guess fail? or i did something wrong

**Comment by Clanceeinfinity** [comment]
this is also the second time i tried this, on my first try i thought i was doing something wrong so i flashed firmware again and started all over, but it doesn't seem like it worked.

**Comment by Archfx** [comment]
Looks like your partition order is messed up currently.

I assume your device is unlocked,  If that is the case, the following steps may work. 

```shell
./fastboot delete-logical-partition system
./fastboot delete-logical-partition system_ext
./fastboot delete-logical-partition product
./fastboot delete-logical-partition system_a
./fastboot delete-logical-partition system_b

./fastboot create-logical-partition system 0

./fastboot flash system aosp-arm64-ab-gapps14.0-20240725.img
```

Let me know the results.

**Comment by Clanceeinfinity** [comment]
what will the command ./fastboot create-logical-partition system 0 do?

will it create a virtual partition? I have more time tomorrow, ill try it out and keep you updated!

**Comment by Archfx** [comment]
I have changed the above answer, first try with the new commands, let's not touch the system partition. We just need to make enough space for the new image, so that the system partition can expand. BTW what is the exact boot partition you deleted?

**Comment by Clanceeinfinity** [comment]
i did the instructions like you put on the side, i have unlocked the bootloader before, then set up the device and enabled usb debugging again, adb reboot fastboot, fastboot devices to see if its connected properly, then i deleted system_ext, and product, then i got my bootslot, it was a, i deleted b then i tried to flash and it said there was too little space, then i deleted a aswell and then it didn't find the file / directory

do you have a telegram, maybe i could send you a video of me trying :0

also rn i reflashed firmware so i can try again

**Comment by Clanceeinfinity** [comment]
ok i tried the commands and it works now, it is booting! interestingly i lost no userdata when installing this

**Comment by Archfx** [comment]
Great!
