### ISSUE TITLE
Navigation bar duplicates when switching between postures

### ISSUE THREAD

**Issue by Sidefix** [Archfx/duo-de#39]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 1
- GSI version: v2024.07.25
- Vendor version:

### Expected Behavior

The navigation bar should always be singular 

### Current Behavior

When switching postures, the navigation bar will get duplicated

Normal/book view:
![20240812_141904](https://github.com/user-attachments/assets/4ae5630e-9952-4cc7-a2e4-dc8aafd01785)

Single screen view, freshly wrapped, no screen rotation:
![20240812_141953](https://github.com/user-attachments/assets/a3a41665-548b-47db-ae52-584d396af643)

### Possible Solution

The issue is fixed if you rotate the screen after going single-screen, but will reoccur after you reopen the screen

### Steps to Reproduce

1. Be in book mode (both screens active)
2. Wrap the device to be in single screen posture
3. 

### Additional context

The doubled navigation bar is not related to the digital assistant; I specifically disabled this

**Comment by Archfx** [comment]
I could not reproduce this issue, Is there any app that this is happening? Are you on desktop mode enabled?

**Comment by Sidefix** [comment]
No, desktop mode is disabled. I've had the issue occur with any app. In the screenshot above it's reproduced with Microsoft Edge.

It is 100% reproducible, bar none. I will record it later and upload a vid.

**Comment by Archfx** [comment]
No worries, I will try again with desktop mode disabled.

**Comment by Archfx** [comment]
Ok, I see the issue when you switch to phone mode from the table mode (when the desktop mode is disabled), the navigation bar is an instance created on top of the original tablet mode navigation bar. If you rotate the device this will refresh correctly and the old navigation bar will vanish. The device will perform as expected!

**Comment by Sidefix** [comment]
@Archfx I don't really understand, why this was closed? I had documented the workaround you provided in my initial issue submission, as requested by the submission form.

I've also tested with Desktop mode on and can absolutely be reproduced with it on as well with the same steps, as long as the app is maximized.

**Comment by Sidefix** [comment]
https://github.com/user-attachments/assets/dc3c3a05-0647-4bca-aef0-854f5120714d

**Comment by Archfx** [comment]
Please read [here](https://github.com/Archfx/duo-de/discussions/47)

I highly recommend you to stay in 12L, or consider any other option since apparently, this ROM contains lots of bugs for your needs.

Note that I have solved issues for a lot of people, but in this case, I don't feel like it. Sorry for that.

**Comment by Archfx** [comment]
This issue is fixed thanks to the observation of @Clanceeinfinity.

**Comment by JengaMasterG** [comment]
I currently switched from 12L and I am seeing this issue on the newest build (2024.09.13). Desktop mode is enabled, and the developer options to support desktop mode are enabled:
Force activities to be resizable
Enable freeform windows
Enable non-resizable in multi-window

**Comment by Archfx** [comment]
> I currently switched from 12L and I am seeing this issue on the newest build (2024.09.13). Desktop mode is enabled, and the developer options to support desktop mode are enabled: Force activities to be resizable Enable freeform windows Enable non-resizable in multi-window

Hi @JengaMasterG,

The latest release is a bit messed up since I tried to address multiple issues simultaneously. I am slowly resolving them one by one. For the moment, you have to disable these options and enable them, the freeform option will prompt a reboot, and once rebooted it will fix the concern.  There is a patch that was created to enable desktop mode automatically, however, that was conflicting with user settings which is why this situation was created. I am reverting back to manual developer options enabling in future releases.

**Comment by JengaMasterG** [comment]
Sounds good! It looks great overall and I'm excited to try it out :)

Thank you for the hard work!
