### ISSUE TITLE
Ambient light sensor from left side screen is never used

### ISSUE THREAD

**Issue by Sidefix** [Archfx/duo-de#40]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 1
- GSI version: v2024.07.25
- Vendor version:

### Expected Behavior

Both sensors should be used depending on posture. For example, when the first screen is exclusively used, only the sensor on its side should be used.

### Current Behavior

Regardless of whether the left, right or both screens are used, only the ambient light sensor on the right is used.
Demo:

https://github.com/user-attachments/assets/cd89f0fb-c10b-414d-98bb-58ff25bdb1e7

### Possible Solution

none identified

### Steps to Reproduce

1. Fold the device to use the left screen
2. Block the ambient light sensor from the right screen
3. 

### Additional context

I know the sensor is functional since it worked fine with vanilla 12L

**Comment by Archfx** [comment]
This is an unhandled scenario in the [PostureProcesor](https://github.com/Archfx/duoPosture), thanks for finding it.

**Comment by Archfx** [comment]
Could you please manually flash the [testing version](https://github.com/Archfx/duo-de/releases/tag/v2024.08.15) (after unzipping) and put the log file here!! Steps are follows,
```shell
adb reboot fastboot
fastboot flash system aosp-arm64-ab-gapps-14.0-<<version>>.img
fastboot reboot 
```

Once the device is booted, use the following command to initiate the log process.

```shell
adb -d logcat | grep POSTURE > log.txt
```
Repeat the steps to use the left side screen mode (Tent Left and Left Phone mode), repeat it for couple of times and do a "ctrl + X" to exit the log process. Include the log file. 

Thanks, Let me know

**Comment by Sidefix** [comment]
I'll need some time for this, please bear with me.

**Comment by Archfx** [comment]
You are good, I obtained the log, fix is not complete yet
