### ISSUE TITLE
The fingerprint sensor is always active, even when the screen is folded closed.

### ISSUE THREAD

**Issue by Sidefix** [Archfx/duo-de#42]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 1
- GSI version: v2024.07.25
- Vendor version:

### Expected Behavior

The fingerprint sensor should be active only when the device is unfolded.

### Current Behavior

The fingerprint sensor on the right screen is active all the time, including when the device is folded closed (with neither screen active). This causes frequent unintentional unlocks while the device is pocketed.

### Possible Solution

n/a

### Steps to Reproduce

1. Turn Surface Duo on
2. Unfold the device
3. Observe fingerprint sensor works as intended
4. Fold the device closed (both screens inward)
5. Tap fingerprint sensor
6. Observe the device vibrates and screens can be seen turning on in the inside

**Comment by Archfx** [comment]
This is the intended behavior of Android, the fingerprint sensor is controlled by `DevicePolicyManager`, and if sensed it will wake the device just to check if the fingerprint is valid or not. For incorrect/ random touches it will not unlock the device or turn on the display.

**Comment by Sidefix** [comment]
@Archfx while I understand that this may be the default intended Android behavior, the behavior is not consistent with vanilla 12L for SD1/2.

I won't insist, but thank you in advance for your consideration.
