### ISSUE TITLE
App drawer is compressed when opened on one screen only on recents app window

### ISSUE THREAD

**Issue by Ethanol10** [Archfx/duo-de#49]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 2
- Build Number: treble_arm64-bgN-userdebug 14 AP2A.240805.005 eng.aruna.20240818.003834
- Vendor version:

### Expected Behavior

The app drawer should behave as it does in the home screen when attempting to open it in the multitasking menu.

### Current Behavior

When opening the app drawer in the multitasking menu, it appears compressed and unusable.

https://github.com/user-attachments/assets/d98f4590-98c7-44c6-907e-7fff925bd901

### Steps to Reproduce

1. Drag up from the bottom to open multitasking
2. Press the app drawer button
3. Menu appears compressed

**Comment by Archfx** [comment]
You are trying to open the app drawer in the recent apps window, that is why this is happening, I will remove the dock in the recent apps when I get the time.

**Comment by Ethanol10** [comment]
I was under the impression it was intended as the app drawer looks normal when accessing it with both screens. But if that's the case then that's no problem then 👍

**Comment by Archfx** [comment]
> I was under the impression it was intended as the app drawer looks normal when accessing it with both screens. But if that's the case then that's no problem then 👍

No worries, It was fixed without disabling it. Will be available in the next big release.

**Comment by sir86** [comment]
this issue happening again on A15
