### ISSUE TITLE
BeNice app pair launcher crashing. 

### ISSUE THREAD

**Issue by lucioarriaga** [Archfx/duo-de#57]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device:  Surface Duo 1
- GSI version: gapps 09.18.2024
- Vendor version:

### Expected Behavior

BeNice lets you assist app pairs so it opens with both apps in Split View. When you open the app pair icon it should open both apps in a Split View with one app to the left and the second app to the right screen. 

### Current Behavior

With the latest version when you try to open it tries to open both apps as floating windows and crashes. It sometimes will open even the last app that was opened. 

### Steps to Reproduce

1. Setup an app pair icon with BeNice app. 
2. Click the app pair icon.
3. You’ll see both apps try load up and crash.

**Comment by Archfx** [comment]
I haven't used this app, but it likely relies on split-screen API calls. When desktop mode is enabled, Android (DUO-DE) attempts to launch the app using floating window APIs instead. These are distinct window management modes that can't run concurrently. You might need to disable desktop mode if you want to use similar apps.

If disabling the desktop mode doesn't solve the issue, it is an issue with this particular app itself.

**Comment by lucioarriaga** [comment]
Thank you I had a feeling that was the case. I thought maybe because I can use split apps option with apps it would still work.
