### ISSUE TITLE
screens not get on when you open device after last build  on duo1

### ISSUE THREAD

**Issue by sir86** [Archfx/duo-de#60]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

Screens shoud get on when you open device

### Current Behavior

screens not get on when you open device after last build . Sometimes it works but most of the time its not  

### Steps to Reproduce

1. 
2. 
3.

**Comment by Archfx** [comment]
It is my bad,  I will fix it in the next revision, until then you have to use the power button or the fingerprint sensor.
