### ISSUE TITLE
Duo 1 Writing system = remote: No such file or directory

### ISSUE THREAD

**Issue by GenTLEmeN85** [Archfx/duo-de#63]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Duo 1
- GSI version: 14
- Vendor version: ?

### Expected Behavior

When i try to flash the img, i got this error:

C:\ADB>fastboot flash system aosp-arm64-ab-gapps-14.0-20241005.img
Sending sparse 'system' 1/14 (262116 KB)           OKAY [  6.336s]
Writing 'system'                                   FAILED (remote: 'No such file or directory')
fastboot: error: Command failed

### Current Behavior

no way to flash into slot a or b!

### Steps to Reproduce

C:\ADB>fastboot flash system aosp-arm64-ab-gapps-14.0-20241005.img
Sending sparse 'system' 1/14 (262116 KB)           OKAY [  6.336s]
Writing 'system'                                   FAILED (remote: 'No such file or directory')
fastboot: error: Command failed

### Additional context

Would be nice if someone can help

**Comment by GenTLEmeN85** [comment]
Im sorry, i didnt see the other topic which solved my problem!

./fastboot delete-logical-partition system_ext_a
./fastboot delete-logical-partition system_ext_b
./fastboot delete-logical-partition product_a
./fastboot delete-logical-partition product_b

./fastboot flash system aosp-arm64-ab-gapps14.0-20240725.img

did it!

Thank you guys, you are awesome!

**Comment by voluptuary** [comment]
Hi, I am getting this error and the listed fix doesn't help. Any ideas?
EDIT: I restored back to factory then tried again using this fix and it then worked.
