### ISSUE TITLE
Phone Mode floating windows option not respected (Duo2)

### ISSUE THREAD

**Issue by Ethanol10** [Archfx/duo-de#64]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo 2
- GSI version: v2024.10.05
- Vendor version:

### Expected Behavior

When in Phone mode (Tent, Ramp, and Brochure Postures) if the option is disabled, apps should open fullscreen.

### Current Behavior

Currently, Tablet mode options control both posture types (Phone and Tablet), and Phone mode toggle doesn't seem to affect how the apps are opened.

### Steps to Reproduce

1. Enable Tablet mode Floating Windows
2. Disable Phone mode Floating Windows
3. Fold phone to phone mode
4. Open an app
5. App appears as a floating window in phone mode and tablet regardless of set option.
6. Disable Tablet mode Floating Windows
7. Enable Phone mode floating windows
7. Open an app
8. App opens full screen, irrespective of phone mode option.

**Comment by Archfx** [comment]
Please try resetting the Trebuchet storage and cache and let me know. It looks like previous user cookies override the updated one.

**Comment by Ethanol10** [comment]
Seems to not change much. Still only working with the tablet mode toggle.

**Comment by Archfx** [comment]
Seriously, I used a variable to check whether the device is in tablet mode or phone mode, looks like for duo2 it does not work. Let me get that variable in another way.

**Comment by Archfx** [comment]
Please check with the updated release and let me know.

**Comment by Ethanol10** [comment]
@Archfx Seems like the release does not have an img file to flash

**Comment by Archfx** [comment]
Sorry, there was an issue with the compile process. 

May I know your `smallest width` size in the phone mode? Go to `Developer options` and search for `smallest width` when you are in phone mode.

**Comment by Ethanol10** [comment]
600dp, I did modify it to try fit more objects.

**Comment by Archfx** [comment]
> 600dp, I did modify it to try fit more objects.

600 is the threshold that I have used to determine the tablet mode and the phone mode, you can use 599 or lower value, and it should solve this issue.

**Comment by Ethanol10** [comment]
That did it, it works fine now!
