### ISSUE TITLE
Trying OTA update crashes

### ISSUE THREAD

**Issue by itsleemcguire** [Archfx/duo-de#65]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version:  2024.10.01
- Vendor version:

### Expected Behavior

OTA Update should start downloading

### Current Behavior

Goes back a step. After trying a few times the message "phhtrebleapp keeps stopping" appears. Can't update and not sure any other way to fix this.

### Steps to Reproduce

1. Try to update
2. 
3.

**Comment by Archfx** [comment]
Try it now, mistakenly OTA file was updated for a test version. It should work now.

**Comment by itsleemcguire** [comment]
I'm getting the same issue now on this, I've tried resetting app permissions and choosing he phh-updater app when trying to get an update, but it's just crashing back to the phh menu when I try to download the update. Any idea what I can do?

**Comment by Archfx** [comment]
> I'm getting the same issue now on this, I've tried resetting app permissions and choosing he phh-updater app when trying to get an update, but it's just crashing back to the phh menu when I try to download the update. Any idea what I can do?

It should work now for the v2024.11.24 release.
