### ISSUE TITLE
Camera issues on duo1  - Saved videos are corrupted

### ISSUE THREAD

**Issue by sir86** [Archfx/duo-de#67]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

stock camera and google camera app that come  with a rom not work but its not a problem cuz you can install any camera app from play store but only taking pics works well, when you try to record video, recorded file is always corrupted and only audio play. i tried like 5 different apps from play store.

### Current Behavior

camera apps should record videos properly. 

### Steps to Reproduce

1. 
2. 
3.

**Comment by sir86** [comment]
nevermind its ok in last update.

**Comment by Archfx** [comment]
Great catch!

**Comment by Archfx** [comment]
Enable the following settings from `settings> Phh Treble Settings`

- `Qualcomm features> Use alternate camera profile`
- `Misc Features> Force Enable Camera2API HAL3`

This should fix this issue.
