### ISSUE TITLE
Fresh install of A15 coming from stock 12L produces an error

### ISSUE THREAD

**Issue by Sidefix** [Archfx/duo-de#80]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: SD1
- GSI version: latest
- Vendor version: latest

### Expected Behavior

Installation should work with the provided instructions

### Current Behavior

I receive the following partitioning error:

 FAILED (remote: 'Not enough space to resize partition')

### Steps to Reproduce

1. Have a locked A12L SD1
2. Unlock bootloader (implicitly wipes data)
3. Perform the required steps as per the project page instructions:

![image](https://github.com/user-attachments/assets/dffde626-e9c6-4aff-a633-a797f08a013b)

### Additional context

Full operations performed below. NO OTHER operations were ran. This device's bootloader is freshly unlocked for the first time prior to running these commands:

![image](https://github.com/user-attachments/assets/de674539-2d17-4d19-8dc2-7cda63cd8c1d)

**Comment by Sidefix** [comment]
For clarity, the device I am utilizing here is **not** the same as the one from #76 

This is a completely separate device that I just unlocked the bootloader for a minute ago for the first time.

**Comment by Ethanol10** [comment]
I saw a discussion post on this before, try this out: 

https://github.com/Archfx/duo-de/discussions/36

**Comment by Sidefix** [comment]
After running the delete operations from the post above, the installation of the image worked successfully.

However after rebooting post-installation, I am now in a bootloop...

![image](https://github.com/user-attachments/assets/a4632b1b-b3a7-4a22-bafd-fa46c8738e19)


@Archfx please help

**Comment by Archfx** [comment]
> After running the delete operations from the post above, the installation of the image worked successfully.
> 
> However after rebooting post-installation, I am now in a bootloop...
> 
> ![image](https://private-user-images.githubusercontent.com/26040103/379059752-a4632b1b-b3a7-4a22-bafd-fa46c8738e19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDUyNzEsIm5iZiI6MTcyOTY0NDk3MSwicGF0aCI6Ii8yNjA0MDEwMy8zNzkwNTk3NTItYTQ2MzJiMWItYjNhNy00YTIyLWJhZmQtZmE0NmM4NzM4ZTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAwNTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGU4YjIwYjY1Y2RiZWUyMzJlNzRlNWUzNjdlYzA2ZDJkMGQ5NmI4MTA1MzkxMjcxMTg5NWFmMWFkZTQ0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w3YHFbPgryp7v_Ouc9vCIYw5IMIoB71B5d2bczLHpcw)
> 
> @Archfx please help

You have to do the factory data reset. It should be good

**Comment by Archfx** [comment]
12L user partition and 15 User partitions are different. That is why it shows this.

**Comment by Sidefix** [comment]
Confirmed. The follow-up factory reset has it boot normally now.

This was quite the mini heart attack since I had followed the instructions quite carefully. It might be worth covering these details in the main page instructions since they are specifically covering transition from 12L.

Thanks for the help.

**Comment by Archfx** [comment]
Lol, this is how it should be prompted when the partitions are not compatible. For your other device, try figuring things out slowly. Remember, to flash a system-related partition, you should be on fastbootd. Fastbootd is for the devices with AB partitions.

**Comment by Archfx** [comment]
> It might be worth covering these details in the main page instructions since they are specifically covering transition from 12L.

Yeah, let me add this actually

**Comment by GumbyXGames** [comment]
> > It might be worth covering these details in the main page instructions since they are specifically covering transition from 12L.
> 
> Yeah, let me add this actually

You really need to update the instructions. They are not there and I almost freaked out thinking I bricked my device
