### ISSUE TITLE
A15 Device getting Locked After Posture Change

### ISSUE THREAD

**Issue by Archfx** [Archfx/duo-de#83]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: All 
- GSI version: A15(all)
- Vendor version:

### Expected Behavior

`system.ui` should not crash.

### Current Behavior

`system.ui` is crashing upon posture translation

```shell
10-20 12:22:28.526  3546  5675 D ConnectivityService: ConnectivityDiagnosticsCallback IBinder died.
10-20 12:22:28.527  3546  6569 E LockoutResetTracker: Callback binder died: android.os.BinderProxy@66da4eb
10-20 12:22:28.527  3546  6569 E LockoutResetTracker: Removing dead callback for: com.android.systemui
```

### Steps to Reproduce

1. Fold to phone mode
2. Unfold to tablet mode
3. The screen is now locked

**Comment by sir86** [comment]
its happening sometimes on A14 too... i use A14 dialy for like 3 months now and happend maybe like 3 times since then.

**Comment by sir86** [comment]
Im on A15 now and yeah its happening all the time now.

**Comment by sir86** [comment]
Its also happens when someones calling,   answer the call by moving phone icon up locking device and you have to unlock  it before u can answer the call.

**Comment by Ethanol10** [comment]
As of v1108, seems like the system UI doesn't crash as much anymore on posture change*, if at all. Can anyone confirm this?

**Comment by mbiebusch** [comment]
Just updated and looks really good! I'll test further, no problems so far. Thanks!

**Comment by Archfx** [comment]
Looks like we are good with this issue.
