### ISSUE TITLE
Unable to Copy or Paste in Floating Windows

### ISSUE THREAD

**Issue by GumbyXGames** [Archfx/duo-de#85]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Surface Duo
- GSI version: treble_arm64_bgN, A15
- Vendor version: 2024.10.22

### Expected Behavior

After selecting text in a floating window, a pop-up should be displayed allowing you to copy the highlighted text 

### Current Behavior

The pop-up doesn't appear. If the app is in full-screen, the pop-up does come up

### Steps to Reproduce

1. Open an app that allows you to copy text
2. Select the text with touch input
3.

**Comment by Archfx** [comment]
I couldn't replicate this issue. Tested on multiple apps including browsers. However, there may be apps that don't support split-screen or floating windows.
