### ISSUE TITLE
Microsoft Start and Bing app not loading error. 

### ISSUE THREAD

**Issue by lucioarriaga** [Archfx/duo-de#86]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: DUO 1
- GSI version: v2024-10-26
- Vendor version:android 15

### Expected Behavior

Microsoft Start and Bing should just load up. 

### Current Behavior

When it attempts to open and load it hangs on a blank screen with loading screen. A configuration error prompt shows up eventually and app never loads up. 
![Screenshot_20241026-121928](https://github.com/user-attachments/assets/01232f76-8049-415c-b2c1-1f4d5340e7df)

### Steps to Reproduce

1. Open up Microsoft Bing or Microsoft Start
2. Leave it attempting to load
3. Error will eventually show on the bottom.

**Comment by Archfx** [comment]
Just to check, try to reproduce this by disabling the floating windows.

**Comment by lucioarriaga** [comment]
> Just to check, try to reproduce this by disabling the floating windows. 

Ok just disabled floating windows and the same behavior happens. I believe this problem used to happen for Android 13 rom that Thai Nguyen once released originally.

**Comment by Archfx** [comment]
Check this issue on the latest version.

**Comment by lucioarriaga** [comment]
Thank you just updated via OTA and same behavior even on latest build.

**Comment by Archfx** [comment]
Ok, I though the issue was with the play integrity checks.

**Comment by lucioarriaga** [comment]
I see the reference I was thinking of from one of the original A13/14 ROMs from Thai Nguyen. Back then the apps were crashing. I do see he made a couple of updates to address it. "Remove displaymask feature to prevent Microsoft apps from crashing" I don't know if that helps. https://xdaforums.com/t/a14-gsi-for-surface-duo.4598441/
