### ISSUE TITLE
Can't OTA update, no apps can perform this function

### ISSUE THREAD

**Issue by itsleemcguire** [Archfx/duo-de#90]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

OTA update should happen 

### Current Behavior

Pop up says No apps can perform this function

### Steps to Reproduce

1. Try to OTA update
2. 
3.

**Comment by Archfx** [comment]
This is due to a change in the updater app in A15, instead select the updater app from `settings> phh Treble Settings> system update`, when prompted to choose the default updater, select the one with the name `phh updater` for always.
