### ISSUE TITLE
Wallpaper app still crashes

### ISSUE THREAD

**Issue by itsleemcguire** [Archfx/duo-de#93]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

Previously there was a mention that the wallpaper app issue was fixed, but if you try to change wallpaper the second you tap on "photos" the app crashes. I can't find any way to set a wallpaper otherwise, any idea?
Pa thanks so much for maintaining this device and rom, it's amazing what you're doing.

### Current Behavior

Crashes to home screen

### Steps to Reproduce

1. Hold on homescreen
2. Wallpaper
3. Choose wallpaper, tap photos, crashes.

**Comment by Archfx** [comment]
I couldn't reproduce the issue. Does anyone else have this issue?
May be try cleaning the wallpaper and styles app cache?

**Comment by itsleemcguire** [comment]
Thank you that solved it, sorry for wasting your time

**Comment by Clanceeinfinity** [comment]
> I couldn't reproduce the issue. Does anyone else have this issue? May be try cleaning the wallpaper and styles app cache?

does work fine for me! i am on the newest a15 build
