### ISSUE TITLE
Unlocking phone wipe all you desktop icons and  widgets 

### ISSUE THREAD

**Issue by sir86** [Archfx/duo-de#95]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: 
- GSI version: 
- Vendor version:

### Expected Behavior

Sometimes when you unlock all you decktop icons and widgets getting wiped and dektop back to default google icons and widget  like you would just install fresh OS.

### Current Behavior

Desktop should not be wiped after unlock.

### Steps to Reproduce

1. 
2. 
3.

**Comment by Archfx** [comment]
Can you reproduce this issue in the latest build?

**Comment by sir86** [comment]
Seems like its ok now.
