### ISSUE TITLE
Not prompted to delete User Data after flashing

### ISSUE THREAD

**Issue by oilcan-productions** [Archfx/duo-de#98]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Duo 2
- GSI version: 2024.11.17
- Vendor version: Don't know where to find that 

### Expected Behavior

The steps in the README list that there is a prompt to delete User Data on the last reboot when coming from 12L.

### Current Behavior

There is no prompt, so the phone technically updates to 15, but some things just don't work so I went and factory reset it from Settings. 
After OOBE things started working (mostly)

### Possible Solution

Reset from Settings rather than during fastboot reboot

### Steps to Reproduce

1.  Unlock a 12L Duo 2 Bootloader
2. Follow the instructions to flash
3. enter the last command fasboot reboot

### Logs

[Uploading reboot.log…]()

**Comment by Archfx** [comment]
It prompts for a user partition wipe, only if the configurations are different. On your case they were compatible, So you are good on this one.

**Comment by Clanceeinfinity** [comment]
I didn't wipe when coming from 12L and 14 too! everything works fine for me
