### ISSUE TITLE
On Screen Keyboard does not pop up automatically when tapping into a text box

### ISSUE THREAD

**Issue by oilcan-productions** [Archfx/duo-de#99]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Duo 2
- GSI version: 2024.11.17
- Vendor version: Don't know

### Expected Behavior

When I tap into an input box in the OS or a webpage the OSK opens at the bottom of the screen

### Current Behavior

Sometimes the sidebar shows up and I can tap the hamburger icon and select On Screen Keyboard for it to show up sometimes the sidebar does not show up at all

### Possible Solution

Unknown

### Steps to Reproduce

1. After flashing and OOBE 
2. Open Setings
3. Tap the Search Bar

**Comment by oilcan-productions** [comment]
Once I switched to Microsoft Swift Key this worked quite well though. Seems to be a GBoard issue

**Comment by alechemy** [comment]
I fixed this by disabling the stylus handwriting toggle in GBoard
